### PR TITLE
Resume retried downloads

### PR DESCRIPTION
**Pull request by MicroDroid**
With this patch downloads are just *resumed* rather than started from scratch.

The patch makes use of the `Range` HTTP header

### CODE REVIEW

**Comment by carlosflorencio** [comment]
Hi, 

Can you remove the .phpintel folder?
I will merge after that.

Thanks!

**Comment by MicroDroid** [comment]
@iamfreee Done.

But, have you actually tested it? At the beginning I had some weird corruptions in the videos, and they automagically got fixed as I was refactoring my implementation a little bit.

After the final changes, I tested it with few videos, I killed the port forcefully with `gdb` during download, seems to work fine. Just curious if it could start corrupting things randomly out of nothing.

**Comment by MicroDroid** [comment]
Hold on a bit, don't merge until I do some more testing

**Comment by carlosflorencio** [comment]
I dont have a subscription to test it. 

So i hope you make it work good :D

**Comment by MicroDroid** [comment]
@iamfree aww :octopus: 

Well, I tested it, it seems to work great, except there was a little issue in string formatting, it's fixed.

However, a new problem arises is that a timed out connection never breaks off and this causes the download process to hang overall. One should make guzzle timeout on reading the socket or something

**Comment by carlosflorencio** [comment]
@MicroDroid i see.

That timeout problem was there before your changes? I have a good internet so i cant test this edge cases.

**Comment by MicroDroid** [comment]
@iamfreee Yeah, it's a guzzle thingy.

The summary of my changes is switching the file to append mode (`a`) and put the downloaded amount of bytes in the `Range` header. Most of everything else was bug fixes to my own implementation

**Comment by carlosflorencio** [comment]
Okay then, i will merge and then wait until someone want to work on the timeout problem.

Many thanks.

**Pull request merged**
