### PR TITLE
New approach to download series

### PR DESCRIPTION
**Pull request by AmirRezaM75**
Hey guys ✋
As mentioned here (#123), new laracasts website uses inertiajs.

IMO it's better than algolia complexity because we can simply access to ``data-page`` attribute and get latest information.
Right now the app scraps topics page and then find all related series and episodes for that topic. It caches response in ``cache.php`` file to don't repeat scraping process from scratch.

probably laracasts removes single **lessons** and added a section called **larabit**. I will add this in future update and after fixing possible bugs.

@carlosflorencio I can share my account details with you for a day to test this.

### CODE REVIEW

**Comment by carlosflorencio** [comment]
Hey @AmirRezaM75 , thanks for your work on this.

With the black friday discount, I went back and subscribed Laracasts again (for the Vim videos at least) so I have an account to test it. After a first run it seems to be working fine 🎉.

I think I'll have time tomorrow to review these changes, I intend to also simplify the docker usage.

**Comment by AmirRezaM75** [comment]
@carlosflorencio
Great
I also subscribed with black Friday discount :)

**Comment by carlosflorencio** [comment]
So I went through the several changes and they all seem fine to merge. I didn't test the several arguments the tool receives and the make skips functionality, those are not in the happy path and can be fixed later if not working correctly.

Just a few minor points if you want to act on:
- When changing the `composer.json` file we should also update the `composer.lock` (via `composer update`)
  - You can push a new `composer.lock` file
- Update `README.md` to have PHP 7 as a requirement and maybe add some paragraph with credits to you

**Comment by AmirRezaM75** [comment]
Yeah I forgot composer.lock
I removed vendor file and  ran ``composer update`` and restart the script to see if anything breaks or not. (it seems fine)
Thanks for offer but I don't agree with credit in readme.md, github's project contributors section is enough for that.

**Comment by carlosflorencio** [comment]
Thank you for the contribution, merged.

**Pull request merged**
