### PR TITLE
Fixed download after major changes at laracasts

### LINKED ISSUE #74: New website layout breaks downloader "2018"
Jeff updates the layout and the downloader is not working anymore:

PHP Notice:  Undefined index: series in D:\tutorials\laracasts-downloader-master-08-08-2018\App\Utils\Utils.php on line 85
PHP Stack trace:
PHP   1. {main}() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:0
PHP   2. App\Downloader->start() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:23
PHP   3. App\Utils\Utils::resolveFaultyLessons() D:\tutorials\laracasts-downloader-master-08-08-2018\App\Downloader.php:109

Notice: Undefined index: series in D:\tutorials\laracasts-downloader-master-08-08-2018\App\Utils\Utils.php on line 85

Call Stack:
    0.4058     384880   1. {main}() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:0
    0.4519    1870880   2. App\Downloader->start() D:\tutorials\laracasts-downloader-master-08-08-2018\start.php:23
    2.4998    3218224   3. App\Utils\Utils::resolveFaultyLessons() D:\tutorials\laracasts-downloader-master-08-08-2018\App\Downloader.php:109

Variables in local scope (#3):
  $array = array ('series' => array (), 'lessons' => array ())
  $episode = *uninitialized*
  $episodes = *uninitialized* ...........................

### PR DESCRIPTION
**Pull request by storrella**
Fixes #74 

After laracasts recent changes, lessons and series cannot be crawled anymore because now that info is loaded via xhr requests through Algolia API. I switched the crawler with an Angolia client and updated README with new intructions.

**The ALGOLIA_APP_ID and ALGOLIA_API_KEY env variables must be filled manually.**

It would be nice if someone does another pr crawling them from the js files

### CODE REVIEW

**Comment by myself379** [comment]
I tested by following your instruction in your updated README.md and its working.

**Comment by carlosflorencio** [comment]
Great work @storrella, thanks for your effort. 💪

Since I can't test it myself, I'll wait for some more feedback before merging.

**Comment by cerberos** [comment]
Thank you @storrella for the commit, it works perfectly now. And a big thank you to @carlosflorencio.

**Comment by carlosflorencio** [comment]
Thanks @storrella. 💪

**Comment by ghost** [comment]
Having a little trouble getting the key and id. I get the following;

o = "x-algolia-api-key" === r || "x-algolia-application-id" === r ? "**hidden for security purposes**" : e[r], t[r] = o

Any recommendations for getting these?

**Comment by haideritx** [comment]
Index Lessons does not exist. Not working for me.

**Pull request merged**
