### PR TITLE
Ability to download from both laracasts and vimeo links

### LINKED ISSUE #138: Series files not downloaded
>  Invalid argument supplied for foreach() in App/Http/Resolver.php on line 207

The code is looking for an array of URLs in a `progressive` property, however on some lessons this is an empty array, resulting in an invalid 104k file to be written, rather than an actual download occurring.  In these cases dash & hls appear to be populated, so maybe files should be pulled directly from one of the cdn entries? 

Relavent portion of the json for the most recent PHP series entry:

```
"request": {
  "files": {
    "dash": {
      "separate_av": true,
      "streams": [
        { "profile": "d0b41bac-2bf2-4310-8113-df764d486192", "quality": "240p", "id": "ee514c77-9f03-4902-adc2-67eff159ca3c", "fps": 30 },
        { "profile": "f9e4a5d7-8043-4af3-b231-641ca735a130", "quality": "540p", "id": "88c86a2d-ca90-469f-b94c-badba23e3825", "fps": 30 },
        { "profile": "5ff7441f-4973-4241-8c2e-976ef4a572b0", "quality": "1080p", "id": "0e4614da-0897-4b9a-85ac-01782d93a784", "fps": 30 },
        { "profile": "c3347cdf-6c91-4ab3-8d56-737128e7a65f", "quality": "360p", "id": "976ac19d-35e0-4bf6-87b0-ab241ec0e3eb", "fps": 30 },
        { "profile": "3df7c5aa-d9f3-4581-930f-f61ddf6e7738", "quality": "1440p", "id": "bebb9862-d0d3-4a9a-b66c-cc4016ef4009", "fps": 30 },
        { "profile": "f3f6f5f0-2e6b-4e90-994e-842d1feeabc0", "quality": "720p", "id": "2b7727df-d4e8-4f0b-8bcd-ca96e4b8bf7e", "fps": 30 }
      ],
      "cdns": {
        "akfire_interconnect_quic": {
          "url": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/ee514c77,88c86a2d,0e4614da,976ac19d,bebb9862,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/master.json?query_string_ranges=1&base64_init=1",
          "origin": "gcs",
          "avc_url": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/ee514c77,88c86a2d,0e4614da,976ac19d,bebb9862,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/master.json?query_string_ranges=1&base64_init=1"
        },
        "fastly_skyfire": {
          "url": "https://skyfire.vimeocdn.com/1665777315-0x32354107162ce0cd4a53f83ea5f072358bda2f61/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/ee514c77,88c86a2d,0e4614da,976ac19d,bebb9862,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/master.json?query_string_ranges=1&base64_init=1", 
          "origin": "gcs",
          "avc_url": "https://skyfire.vimeocdn.com/1665777315-0x32354107162ce0cd4a53f83ea5f072358bda2f61/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/ee514c77,88c86a2d,0e4614da,976ac19d,bebb9862,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/master.json?query_string_ranges=1&base64_init=1"
        }
      },
      "streams_avc": [
        { "profile": "d0b41bac-2bf2-4310-8113-df764d486192", "quality": "240p", "id": "ee514c77-9f03-4902-adc2-67eff159ca3c", "fps": 30 },
        { "profile": "f9e4a5d7-8043-4af3-b231-641ca735a130", "quality": "540p", "id": "88c86a2d-ca90-469f-b94c-badba23e3825", "fps": 30 },
        { "profile": "5ff7441f-4973-4241-8c2e-976ef4a572b0", "quality": "1080p", "id": "0e4614da-0897-4b9a-85ac-01782d93a784", "fps": 30 },
        { "profile": "c3347cdf-6c91-4ab3-8d56-737128e7a65f", "quality": "360p", "id": "976ac19d-35e0-4bf6-87b0-ab241ec0e3eb", "fps": 30 },
        { "profile": "3df7c5aa-d9f3-4581-930f-f61ddf6e7738", "quality": "1440p", "id": "bebb9862-d0d3-4a9a-b66c-cc4016ef4009", "fps": 30 },
        { "profile": "f3f6f5f0-2e6b-4e90-994e-842d1feeabc0", "quality": "720p", "id": "2b7727df-d4e8-4f0b-8bcd-ca96e4b8bf7e", "fps": 30 }
      ],
      "default_cdn": "akfire_interconnect_quic"
    },
    "hls": {
      "separate_av": true,
      "default_cdn": "akfire_interconnect_quic",
      "cdns": {
        "akfire_interconnect_quic": {
          "url": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&external-subs=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1",
          "origin": "gcs",
          "captions": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1",
          "avc_url": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&external-subs=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1"
        },
        "fastly_skyfire": {
          "url": "https://skyfire.vimeocdn.com/1665777315-0x32354107162ce0cd4a53f83ea5f072358bda2f61/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&external-subs=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1",
          "origin": "gcs",
          "captions": "https://skyfire.vimeocdn.com/1665777315-0x32354107162ce0cd4a53f83ea5f072358bda2f61/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1",
          "avc_url": "https://skyfire.vimeocdn.com/1665777315-0x32354107162ce0cd4a53f83ea5f072358bda2f61/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&external-subs=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1"
        }
      },
      "captions": "https://147vod-adaptive.akamaized.net/exp=1665777315~acl=%2Fcdefc022-8ee6-40dd-8bf9-d9f9577ca86a%2F%2A~hmac=b25732d16c5e5a69a86e61a38004bb1599281ea7632dbb4acfc4d49f351de555/cdefc022-8ee6-40dd-8bf9-d9f9577ca86a/sep/video/0e4614da,bebb9862,88c86a2d,976ac19d,ee514c77,2b7727df/audio/7ecc14fb,1e86422b,4e4fafd4/subtitles/47646381-English%20%28auto-generated%29-en-x-autogen-cc/master.m3u8?subcache=1&subtoken=750e751d4cb8312eff5bcde551dc5534e491e110a73232b5f9b6781929858fd1&query_string_ranges=1"
    },
    "progressive": []
  }
  /* ... */
}
```

### PR DESCRIPTION
**Pull request by AmirRezaM75**
Fix https://github.com/carlosflorencio/laracasts-downloader/issues/138

The app extracts Vimeo links from progressive array

https://github.com/carlosflorencio/laracasts-downloader/blob/c4bdd3331b6e457490dd70bf63a4dd6757150531/App/Http/Resolver.php#L201

There are two possible problems with this approache:

1. Sometimes this array doesn't contains all various qualities and usually contains lowest resolution.
2. The array may be empty.

I fix these issues with a new approach but that relies on [ffmpeg](https://ffmpeg.org/) under the hood.
with this approach you can download customized quality and ignore laracasts throttling. But if you think installing FFmpeg is a headache for you still can set ``DOWNLOAD_SOURCE=laracasts`` and use Laracast's direct link.

I'm still testing it and currently downloading from laracasts iteself and will download from vimeo when it exceeds laracasts limit. Then will update README and share the result here.

### CODE REVIEW

**Comment by AmirRezaM75** [comment]
@willvincent please test it out if you can.

**Comment by AmirRezaM75** [comment]
Here is the result of ``SOURCE_DOWNLOAD=laracasts``
```
====================================
Downloading
====================================
> 77 new episodes. 24.097s elapsed with 8.00Mb of memory usage.

====================================
Downloading Series
====================================

> Download started: 26 - The Gambler's Ruin, Illustrated With PHP . . . . Saving on series/jeffreys-larabits
> Elapsed time: 289.258s, Memory: 8.00Mb%)      
> Current: 1 of 77 total. Left: 76

> Download started: 27 - 6 New'ish HTML Tags You Can Use Right Now . . . . Saving on series/jeffreys-larabits
> Elapsed time: 266.462s, Memory: 8.00Mb%)      
> Current: 2 of 77 total. Left: 75

> Download started: 28 - Tiny Refactors Make a Big Difference . . . . Saving on series/jeffreys-larabits
> Elapsed time: 376.794s, Memory: 8.00Mb%)      
> Current: 3 of 77 total. Left: 74

> Download started: 29 - Laravel's New Strict Mode . . . . Saving on series/jeffreys-larabits
> Elapsed time: 301.556s, Memory: 8.00Mb%)      
> Current: 4 of 77 total. Left: 73

> Download started: 29 - Bringing Page Transitions to the Web . . . . Saving on series/andres-larabits
> Elapsed time: 227.765s, Memory: 8.00Mb      
> Current: 5 of 77 total. Left: 72

> Download started: 30 - A New Kind of Static Site Generator . . . . Saving on series/andres-larabits
> Elapsed time: 257.713s, Memory: 8.00Mb%)      
> Current: 6 of 77 total. Left: 71

> Download started: 01 - First Look at CSS Grid . . . . Saving on series/css-grids-simplified
> Elapsed time: 55.979s, Memory: 8.00Mb)      
> Current: 7 of 77 total. Left: 70

> Download started: 02 - Sizing Cells . . . . Saving on series/css-grids-simplified
> Elapsed time: 52.294s, Memory: 8.00Mb      
> Current: 8 of 77 total. Left: 69

> Download started: 03 - Creating Rows . . . . Saving on series/css-grids-simplified
> Elapsed time: 76.109s, Memory: 8.00Mb)      
> Current: 9 of 77 total. Left: 68

> Download started: 04 - Spacing Between Cells . . . . Saving on series/css-grids-simplified
> Elapsed time: 91.569s, Memory: 8.00Mb)      
> Current: 10 of 77 total. Left: 67

> Download started: 05 - Horizontal and Vertical Spacing . . . . Saving on series/css-grids-simplified
> Elapsed time: 61.866s, Memory: 8.00Mb)      
> Current: 11 of 77 total. Left: 66

> Download started: 06 - Single Cell Alignment . . . . Saving on series/css-grids-simplified
> Elapsed time: 71.873s, Memory: 8.00Mb)      
> Current: 12 of 77 total. Left: 65

> Download started: 07 - Merge and Swap Cells . . . . Saving on series/css-grids-simplified
> Elapsed time: 71.103s, Memory: 8.00Mb)      
> Current: 13 of 77 total. Left: 64

> Download started: 08 - Named Grid Areas . . . . Saving on series/css-grids-simplified
> Elapsed time: 82.755s, Memory: 8.00Mb)      
> Current: 14 of 77 total. Left: 63

> Download started: 09 - Advanced Sizing Values . . . . Saving on series/css-grids-simplified
> Elapsed time: 101.267s, Memory: 8.00Mb      
> Current: 15 of 77 total. Left: 62

> Download started: 10 - Responsive Grids Without Media Queries . . . . Saving on series/css-grids-simplified
> Elapsed time: 73.941s, Memory: 8.00Mb)      
> Current: 16 of 77 total. Left: 61

> Download started: 11 - Auto Flow and Sizing Implicit Grids . . . . Saving on series/css-grids-simplified
> Elapsed time: 101.187s, Memory: 8.00Mb      
> Current: 17 of 77 total. Left: 60

> Download started: 12 - Put Your Learning to the Test . . . . Saving on series/css-grids-simplified
> Elapsed time: 73.776s, Memory: 8.00Mb)      
> Current: 18 of 77 total. Left: 59

> Download started: 01 - Introduction . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 56.629s, Memory: 8.00Mb)      
> Current: 19 of 77 total. Left: 58

> Download started: 02 - Configuration . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 81.084s, Memory: 8.00Mb)      
> Current: 20 of 77 total. Left: 57

> Download started: 03 - Deploy a Node Function . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 64.510s, Memory: 8.00Mb)      
> Current: 21 of 77 total. Left: 56

> Download started: 04 - Deploy a Python Function . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 21.577s, Memory: 8.00Mb       
> Current: 22 of 77 total. Left: 55

> Download started: 05 - Browser Automation . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 94.425s, Memory: 8.00Mb)      
> Current: 23 of 77 total. Left: 54

> Download started: 06 - A Performance Trick . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 54.577s, Memory: 8.00Mb      
> Current: 24 of 77 total. Left: 53

> Download started: 07 - Adding Layers . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 60.476s, Memory: 8.00Mb)      
> Current: 25 of 77 total. Left: 52

> Download started: 08 - Serverless Browsershot . . . . Saving on series/developing-serverless-functions-in-laravel
> Elapsed time: 90.728s, Memory: 8.00Mb      
> Current: 26 of 77 total. Left: 51

> Download started: 09 - Separating by Environment . . . . Saving on series/developing-serverless-functions-in-laravel
> Client error response [url] https://laracasts.com/downloads/eyJpdiI6IjNJdW4zNzh5Q3c0VlBoYUpaRXZYZHc9PSIsInZhbHVlIjoiY3JyaExnSE1SeHl3SW95dzlBWVVVUT09IiwibWFjIjoiMDFkNDFmY2UwZjUzY2RjZGVhM2I5MGY3NzNkNDFiNDE3MjVhZDg5Zjc0ODY0MjUwMjYyZDAwYmJlMWFhMDlhMSIsInRhZyI6IiJ9 [status code] 429 [reason phrase] Too Many Requests
> Current: 27 of 77 total. Left: 50
```

**Comment by AmirRezaM75** [comment]
SOURCE_DOWNLOAD=vimeo
```
====================================
Downloading
====================================
> 52 new episodes. 30.257s elapsed with 8.00Mb of memory usage.

====================================
Downloading Series
====================================

> Download started: 09 - Separating by Environment . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 14.43 MB of 14.43 MB (100%)      
> Downloading audio...
> Current: 1 of 52 total. Left: 5100%)        

> Download started: 10 - Deploying Your Functions . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 11.94 MB of 11.94 MB (100%)      
> Downloading audio...
> Current: 2 of 52 total. Left: 5000%)        

> Download started: 11 - Environment Variables . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 11.42 MB of 11.42 MB (100%)      
> Downloading audio...
> Current: 3 of 52 total. Left: 49         

> Download started: 12 - Executing in Parallel . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 17.21 MB of 17.21 MB (100%)      
> Downloading audio...
> Current: 4 of 52 total. Left: 48(100%)      

> Download started: 13 - Async Execution . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 21.94 MB of 21.94 MB (100%)      
> Downloading audio...
> Current: 5 of 52 total. Left: 47(100%)      

> Download started: 14 - Fire-and-Forget Execution . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 15.79 MB of 15.79 MB (100%)      
> Downloading audio...
> Current: 6 of 52 total. Left: 46(100%)      

> Download started: 15 - Warming . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 12.53 MB of 12.53 MB (100%)      
> Downloading audio...
> Current: 7 of 52 total. Left: 45(100%)      

> Download started: 16 - Debugging . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 22.19 MB of 22.19 MB (100%)      
> Downloading audio...
> Current: 8 of 52 total. Left: 44(100%)      

> Download started: 17 - Goodbye and Next Steps . . . . Saving on series/developing-serverless-functions-in-laravel

> Downloading video...
> Downloaded 13.68 MB of 13.68 MB (100%)      
> Downloading audio...
> Current: 9 of 52 total. Left: 4300%)        

> Download started: 01 - Charts and Queries . . . . Saving on series/laravel-cookbook
```

**Comment by willvincent** [comment]
I'll have to do more testing, and find existing invalid files/etc but on my first attempt there was nothing to download.

But, based on your logs it looks like you probably fixed it.

**Pull request merged**
