### PR TITLE
Add retry download config flag

### PR DESCRIPTION
**Pull request by antonkomarev**
Related to #34

### CODE REVIEW

**Comment by carlosflorencio** [comment]
Very nice, thanks! :D

**Comment by antonkomarev** [comment]
Np. Thanks for maintaining the tool for awesome dev resource!

**Comment by antonkomarev** [comment]
It's not handling all connection errors, but most of them at least.

**Comment by carlosflorencio** [comment]
Okay. I can't test it, so your feedback is very appreciated.

**Pull request merged**
