### PR TITLE
Get real episode count since algolia episode count is wrong on newer …

### PR DESCRIPTION
**Pull request by mattias**
…series/episodes.

Instead of using the Algolia episode count, it checks the series page and reads the episode count from there. It's worse than using Algolia directly but Algolia episode count is apparently not up to date, so this fixes that.

Notice that the composer.lock is updated and included with this commit. Works for me with php 7.3.

### CODE REVIEW

**Comment by carlosflorencio** [comment]
@mattias thanks for your work! 🏅 

@haideritx @Lambik @ashickur-rahman @mouson can you guys test this fix?

**Comment by Lambik** [comment]
I tested it with my current setup of not-having-all-videos and the skip files, and it worked.
I made the new skip files, tried again, didn't download anything (correct).
I made it download into a new folder without skip files, it found the correct amount of lessons and series (i didn't let it download all 1100+ files, but i assume it works).

So for me it works correctly. Sure it bombards the server a bit more with the extra requests, but then again, that's how scraping works :P

**Comment by mouson** [comment]
that is worked for me

**Comment by carlosflorencio** [comment]
@mattias can you update the working date on the readme? 

Will merge after that, thanks!

**Comment by mattias** [comment]
I've updated the working date. Assumed it was MM/DD/YYYY.

**Comment by carlosflorencio** [comment]
@mattias merged, thanks for your efforts!

**Comment by Lambik** [comment]
@mattias indeed, thanks a bunch!

**Pull request merged**
